/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sc.senac.br.view;

import java.awt.Dimension;
import sc.senac.br.control.EncomendaControl;

/**
 *
 * @author hvb
 */
public class ListarEncomenda extends javax.swing.JInternalFrame {

    private EncomendaControl encCtrl;

    public ListarEncomenda() {
        initComponents();
        encCtrl = new EncomendaControl(tbEncomenda, tbEncomendaProduto, tfPesquisaCliente, total);
        encCtrl.listarAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbEncomenda = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEncomendaProduto = new javax.swing.JTable();
        tfPesquisaCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        excluirProd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        tbEncomenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Encomenda", "Nome", "Data Pedido", "Data Entrega", "Entregador", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEncomenda.getTableHeader().setReorderingAllowed(false);
        tbEncomenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbEncomendaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbEncomenda);
        if (tbEncomenda.getColumnModel().getColumnCount() > 0) {
            tbEncomenda.getColumnModel().getColumn(0).setResizable(false);
            tbEncomenda.getColumnModel().getColumn(1).setResizable(false);
            tbEncomenda.getColumnModel().getColumn(2).setResizable(false);
            tbEncomenda.getColumnModel().getColumn(3).setResizable(false);
            tbEncomenda.getColumnModel().getColumn(4).setResizable(false);
            tbEncomenda.getColumnModel().getColumn(5).setResizable(false);
        }

        tbEncomendaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Valor", "quantidade", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEncomendaProduto.getTableHeader().setReorderingAllowed(false);
        tbEncomendaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbEncomendaProdutoMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbEncomendaProduto);
        if (tbEncomendaProduto.getColumnModel().getColumnCount() > 0) {
            tbEncomendaProduto.getColumnModel().getColumn(0).setResizable(false);
            tbEncomendaProduto.getColumnModel().getColumn(1).setResizable(false);
            tbEncomendaProduto.getColumnModel().getColumn(2).setResizable(false);
            tbEncomendaProduto.getColumnModel().getColumn(3).setResizable(false);
        }

        tfPesquisaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaClienteKeyReleased(evt);
            }
        });

        jLabel1.setText("Digite o nome do cliente");

        jLabel2.setText("Total: R$");

        excluirProd.setText("Excluir Produto");
        excluirProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirProdActionPerformed(evt);
            }
        });

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(excluirProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                            .addComponent(tfPesquisaCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(115, 115, 115)
                        .addComponent(jButton1)
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(excluirProd))
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbEncomendaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEncomendaMouseReleased
        encCtrl.enviarEncomenda();
        encCtrl.getEncProdCtrl().listarAction();
    }//GEN-LAST:event_tbEncomendaMouseReleased

    private void tbEncomendaProdutoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEncomendaProdutoMouseReleased
        encCtrl.enviarEncomenda();
    }//GEN-LAST:event_tbEncomendaProdutoMouseReleased

    private void tfPesquisaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaClienteKeyReleased
        encCtrl.pesquisarAction();
    }//GEN-LAST:event_tfPesquisaClienteKeyReleased

    private void excluirProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirProdActionPerformed
        encCtrl.getEncProdCtrl().excluirAction();
        encCtrl.getEncProdCtrl().listarAction();
    }//GEN-LAST:event_excluirProdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        encCtrl.excluirAction();
        encCtrl.listarAction();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        encCtrl.listarAction();
        encCtrl.getEncProdCtrl().listarAction();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton excluirProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbEncomenda;
    private javax.swing.JTable tbEncomendaProduto;
    private javax.swing.JTextField tfPesquisaCliente;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
